name: Laravel CI Test

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: testing_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup Laravel Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: testing_db
          DB_USERNAME: user
          DB_PASSWORD: password
          DB_HOST: 127.0.0.1
        run: php artisan migrate --force

      # Check PHP code formatting with PHPFMT
      - name: Run PHPFMT
        run: ./vendor/bin/phpmd app,routes text codesize,controversial,design,naming,unusedcode

      # Static analysis using Larastan
      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse app routes --memory-limit=2G
