name: Static Analysis (Larastan)

on: [push, pull_request]

jobs:
  larastan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Composer Dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse app routes --memory-limit=2G